GET http://localhost:3001/api/notes/

###

GET http://localhost:3001/api/notes/6157ede530a902ab0e774c58

###

POST http://localhost:3001/api/notes/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxNWJjMzY1NjI3MDdmZDNkN2U0MTdkZCIsImlhdCI6MTYzMzQ5OTIwMiwiZXhwIjoxNjMzNTAyODAyfQ.GxTwCrtY1cWlJxxeOFxXBYQ97pf--eP_ByCaKgzd-Vw

{
    "content": "Material UI is awesome!"
}

###

DELETE  http://localhost:3001/api/notes/6157bce9d279bdfa4a976c65

###

GET http://localhost:3001/unknown

###

PUT http://localhost:3001/api/notes/6157c5eb269e901ddc1cf55b
content-type: application/json

{
  "content": "VS code is awesome",
  "important": false
}

