GET http://localhost:3001/api/users/

###

POST http://localhost:3001/api/users/
content-type: application/json

{
    "username": "admin",
    "name": "Admin",
    "password": "admin"
}

###

POST http://localhost:3001/api/login/
content-type: application/json

{
    "username": "root",
    "password": "salainen"
}